[package]
name = "httpx"
version = "0.1.0"
edition = "2021"

[dependencies]
http = "0.2.8"
http-serde = "1.1"
ureq = "2.10"
url = "2.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"